In [3]:
import numpy as np
a=np.array([[1,2,3],[7,6,8]])
print(a)

[[1 2 3]
 [7 6 8]]


In [4]:
b=a.reshape(6,1)
print(b)

[[1]
 [2]
 [3]
 [7]
 [6]
 [8]]


In [5]:
c=np.zeros((2,2))
d=np.ones((3,3))
print(np.sum(c),'\n',d.dtype,np.sum(d,axis=0))

0.0 
 float64 [ 3.  3.  3.]


In [6]:
a=np.arange(10)
%matplotlib inline

In [7]:
from matplotlib import pyplot as plt


In [57]:
x = np.random.randn(4, 3, 3, 2)
print(x)

[[[[-0.53250399 -0.32891854]
   [ 2.2456814  -0.7657499 ]
   [-0.59384671  0.30082055]]

  [[-0.68701085  0.44621817]
   [ 0.01261861 -1.12060409]
   [-0.89379984 -1.3283859 ]]

  [[ 0.4141009  -0.21527151]
   [ 1.31942416 -1.39055798]
   [-0.04724485 -1.30822648]]]


 [[[ 1.57113665  1.08093504]
   [ 0.1255856  -0.6104798 ]
   [-0.45851885 -0.08300936]]

  [[ 0.52901284  0.55426141]
   [ 0.00973448 -1.40651062]
   [-1.17231651  0.52128273]]

  [[-0.69047066 -0.0804845 ]
   [-1.79931627 -0.48556748]
   [ 0.58567994 -0.46402183]]]


 [[[ 1.81144522  1.1001897 ]
   [-0.16313803 -0.62086844]
   [-2.56820051 -0.05292223]]

  [[-1.96301139  1.25762041]
   [-0.02085645 -0.53817518]
   [-1.01454338 -0.36698081]]

  [[-0.566742    0.08689656]
   [ 1.39504187  0.54837316]
   [-0.90002892 -0.56147226]]]


 [[[-1.35375738 -1.2623157 ]
   [ 2.40636946 -0.82869209]
   [-1.49340527  0.97754628]]

  [[-0.27324978  0.31001683]
   [-1.49072992  0.77467003]
   [ 0.64876988  0.31853875]]

  [[ 0.0440081 

In [60]:
print(x[3,0])

[[-1.35375738 -1.2623157 ]
 [ 2.40636946 -0.82869209]
 [-1.49340527  0.97754628]]
