## NumPy


NumPy, which stands for Numerical Python, is a library which basically allows you to perform logical and mathematical operations on an array. The most important object defined in NumPy is an N-dimensional array type called ndarray . In this example we are creating a 2x2 array and assigning it to a

In [2]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

Now what happens with array is that you would want to change its shape somethings for manipulation . 


In [10]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,9)
b

ValueError: cannot reshape array of size 6 into shape (3,9)

Numpy also provides many functions to create arrays:

In [4]:

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]


#### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. 

In [14]:

x = np.array()   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

                        # Prints "int64"

TypeError: Required argument 'object' (pos 1) not found

Computational Purposes

In [7]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

10
[4 6]


### SLicing and indexing
In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 7, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.

In [15]:
a=np.arange(10)
s = slice(2,7,2)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Numpy with histogram
NumPy has a numpy.histogram() function that is a graphical representation of the frequency distribution of data. Rectangles of equal horizontal size corresponding to class interval called bin and variable height corresponding to frequency.

In [4]:
from matplotlib import pyplot as plt 
import numpy as np  
   
a = np.array([1,2,65,66]) 
plt.hist(a, bins = [0,20,40,60,80,100]) 
plt.title("histogram") 
plt.show()