In [2]:
import numpy as np
from sklearn.cross_validation import train_test_split # new version has it in model_selection
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.cross_validation import cross_val_score

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
np.random.seed(20)
X, y = np.random.randn(10, 3), np.random.rand(10) # filling in random numbers for input and output datasets

In [4]:
X

array([[ 0.88389311,  0.19586502,  0.35753652],
       [-2.34326191, -1.08483259,  0.55969629],
       [ 0.93946935, -0.97848104,  0.50309684],
       [ 0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266],
       [ 0.24571517, -0.0441948 ,  1.56763255],
       [ 1.05110868,  0.40636843, -0.1686461 ],
       [-3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737],
       [ 1.55618644,  0.12877835, -2.06694872]])

In [5]:
y

array([ 0.26362883,  0.31051155,  0.62685344,  0.55744981,  0.31857956,
        0.39484322,  0.25797459,  0.58224112,  0.16162871,  0.59813382])

it's fine if you can't grasp all the details below. this requires some theory of ML

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25) # shuffle will be true by default

In [7]:
model = linear_model.LinearRegression() # instantiating a linear model to model

In [8]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
ans = model.predict(X_test)

In [10]:
mean_squared_error(ans, y_test)

0.049372851300781874

In [11]:
cross_val_score(model, X, y) # scores in 3 folds cv

array([-1.85742719, -5.56779849, -2.74753261])